-- Run as ADMIN. Password is prompted and never stored in this file.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON VERIFY OFF

ACCEPT training_password CHAR PROMPT 'TRAINING password: ' HIDE

CREATE USER TRAINING IDENTIFIED BY "&&training_password"
  DEFAULT TABLESPACE DATA
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO TRAINING;
GRANT EXECUTE ON DBMS_CLOUD TO TRAINING;
GRANT EXECUTE ON DBMS_CLOUD_AI TO TRAINING;
GRANT EXECUTE ON DBMS_VECTOR TO TRAINING;
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO TRAINING;

BEGIN
  DBMS_CLOUD_ADMIN.ENABLE_RESOURCE_PRINCIPAL();
  DBMS_CLOUD_ADMIN.ENABLE_RESOURCE_PRINCIPAL(username => 'TRAINING');
END;
/

SELECT privilege
  FROM DBA_SYS_PRIVS
 WHERE grantee = 'TRAINING'
 ORDER BY privilege;

UNDEFINE training_password
EXIT SUCCESS
