-- Run as TRAINING after DBMS_VECTOR credential TRAINING_VECTOR_CRED is registered.
-- The public script contains no private key or token.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON

DEFINE vector_endpoint = '&1'
DEFINE embedding_model = '&2'

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE TRAINING_QA_EXAMPLE (
      EXAMPLE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      QUESTION CLOB NOT NULL,
      ANSWER_SQL CLOB NOT NULL,
      EMBEDDING VECTOR(1536, FLOAT32) NOT NULL,
      CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
    )]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE FUNCTION training_vector_params RETURN CLOB AUTHID DEFINER IS
BEGIN
  RETURN TO_CLOB('{"provider":"ocigenai","credential_name":"TRAINING_VECTOR_CRED",')
    || TO_CLOB('"url":"&&vector_endpoint","model":"&&embedding_model","truncate":"END"}');
END;
/

CREATE OR REPLACE FUNCTION training_qa_search(
  p_question IN CLOB,
  p_top_k IN PLS_INTEGER DEFAULT 3
) RETURN SYS_REFCURSOR AUTHID DEFINER IS
  l_query VECTOR;
  l_result SYS_REFCURSOR;
BEGIN
  l_query := DBMS_VECTOR.UTL_TO_EMBEDDING(p_question, JSON(training_vector_params()));
  OPEN l_result FOR
    SELECT example_id, question, answer_sql,
           VECTOR_DISTANCE(embedding, l_query, COSINE) AS cosine_distance
      FROM training_qa_example
     ORDER BY VECTOR_DISTANCE(embedding, l_query, COSINE), example_id
     FETCH FIRST LEAST(GREATEST(NVL(p_top_k, 3), 1), 20) ROWS ONLY;
  RETURN l_result;
END;
/

-- ASCII sample avoids client encoding ambiguity. For Korean questions, use the
-- UTF-8 Base64 reconstruction pattern documented in README.md. Store the
-- example only when it does not already exist.
MERGE INTO training_qa_example t
USING (
  SELECT TO_CLOB('How many standard active users were there on 2026-07-15?') question,
         TO_CLOB('SELECT COUNT(DISTINCT GUID) FROM GAME_USER_MST WHERE BASE_DT = DATE ''2026-07-15'' AND AU_FLAG = 1 AND EXPT_USER_YN = ''N''') answer_sql
    FROM dual
) s
ON (DBMS_LOB.COMPARE(t.question, s.question) = 0)
WHEN NOT MATCHED THEN INSERT (question, answer_sql, embedding)
VALUES (
  s.question,
  s.answer_sql,
  DBMS_VECTOR.UTL_TO_EMBEDDING(
    TO_CLOB('Question: ') || s.question || CHR(10) || TO_CLOB('Answer SQL: ') || s.answer_sql,
    JSON(training_vector_params())
  )
);

COMMIT;

SELECT example_id,
       CASE WHEN embedding IS NULL THEN 'N' ELSE 'Y' END AS embedding_yn
  FROM training_qa_example
 ORDER BY example_id;

UNDEFINE vector_endpoint
UNDEFINE embedding_model
EXIT SUCCESS
