-- OAPC 3rd lab vector search demo with real OCI GenAI embeddings
--
-- Run as the assigned TRAINxx user after GENAI_VECTOR_CRED has been created.
-- Credential creation is done by:
--   scripts/oapc_create_vector_credentials_from_oci_config.py
--
-- Embedding model:
--   cohere.embed-v4.0 via OCI Generative AI
--
-- Scenario:
--   Northwind customer support policy snippets for return, shipping, inventory,
--   and discount questions. The demo stores text embeddings in Oracle VECTOR
--   columns and searches them with VECTOR_DISTANCE.

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO   l_count
  FROM   user_credentials
  WHERE  credential_name = 'GENAI_VECTOR_CRED';

  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(
      -20001,
      'GENAI_VECTOR_CRED is missing. Run scripts/oapc_create_vector_credentials_from_oci_config.py first.'
    );
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE support_policy_vectors PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE support_policy_vectors (
  doc_id      NUMBER PRIMARY KEY,
  policy_area VARCHAR2(30) NOT NULL,
  title       VARCHAR2(200) NOT NULL,
  doc_text    CLOB NOT NULL,
  tags        VARCHAR2(400),
  doc_vector  VECTOR(1536, FLOAT32)
);

COMMENT ON TABLE support_policy_vectors IS
'Northwind customer support policy snippets embedded with OCI GenAI cohere.embed-v4.0.';
COMMENT ON COLUMN support_policy_vectors.doc_vector IS
'VECTOR(1536,FLOAT32) embedding generated by DBMS_VECTOR.UTL_TO_EMBEDDING using cohere.embed-v4.0.';

INSERT INTO support_policy_vectors (doc_id, policy_area, title, doc_text, tags) VALUES (
  1,
  'RETURN',
  'Damaged or defective item return',
  'If a customer reports a damaged, defective, or broken product, verify the order number first. If the order exists, create an RMA number and set the return status to PENDING. Ask for a photo only when the damage is disputed.',
  'return,refund,rma,damaged,defective,반품,환불,파손,불량'
);

INSERT INTO support_policy_vectors (doc_id, policy_area, title, doc_text, tags) VALUES (
  2,
  'RETURN',
  'Refund timing after return approval',
  'Refunds are processed after the returned item is received or after a manager approves an exception. Standard refund time is three to five business days. Shipping charges are refunded only when the issue was caused by Northwind.',
  'refund,return,shipping charge,환불,반품,배송비'
);

INSERT INTO support_policy_vectors (doc_id, policy_area, title, doc_text, tags) VALUES (
  3,
  'SHIPPING',
  'Delayed shipment handling',
  'For delayed shipments, check the order date, required date, shipped date, and freight information. If shipped_date is missing, explain that the order has not shipped yet and escalate when the required date has passed.',
  'shipping,delivery,delay,freight,배송,지연,운송'
);

INSERT INTO support_policy_vectors (doc_id, policy_area, title, doc_text, tags) VALUES (
  4,
  'SHIPPING',
  'Shipping address correction',
  'A shipping address can be changed only before the shipment is released. If shipped_date already exists, create a follow-up case instead of changing the original order address.',
  'shipping,address,delivery,change,배송,주소,변경'
);

INSERT INTO support_policy_vectors (doc_id, policy_area, title, doc_text, tags) VALUES (
  5,
  'INVENTORY',
  'Out-of-stock and backorder response',
  'When units_in_stock is zero and units_on_order is greater than zero, tell the customer the product is on backorder. If reorder_level is high, suggest an alternative product from the same category.',
  'stock,inventory,backorder,reorder,재고,품절,입고'
);

INSERT INTO support_policy_vectors (doc_id, policy_area, title, doc_text, tags) VALUES (
  6,
  'INVENTORY',
  'Discontinued product guidance',
  'If discontinued is 1, do not promise restock. Search for active products in the same category and explain that the discontinued item is no longer available.',
  'discontinued,substitute,category,단종,대체상품,재고'
);

INSERT INTO support_policy_vectors (doc_id, policy_area, title, doc_text, tags) VALUES (
  7,
  'PRICE',
  'Bulk discount and price quote',
  'For bulk discount requests, confirm product id, quantity, unit price, and discount policy. A discount must be shown separately from the base unit price and should not overwrite the product master price.',
  'price,discount,quote,bulk,가격,할인,견적'
);

INSERT INTO support_policy_vectors (doc_id, policy_area, title, doc_text, tags) VALUES (
  8,
  'PRICE',
  'Order total explanation',
  'When explaining an order total, calculate line amount as unit_price times quantity times one minus discount. Add freight separately and clearly distinguish item discount from shipping cost.',
  'order,total,discount,freight,주문금액,할인,배송비'
);

INSERT INTO support_policy_vectors (doc_id, policy_area, title, doc_text, tags) VALUES (
  9,
  'MIXED',
  'International shipment and return exception',
  'For international shipments, return approval may require manager review because freight and customs charges are handled separately. Explain that the product refund and shipping refund can have different decisions.',
  'international,shipping,return,customs,해외배송,반품,관세'
);

COMMIT;

DECLARE
  c_embedding_params CONSTANT CLOB := '{
    "provider": "ocigenai",
    "credential_name": "GENAI_VECTOR_CRED",
    "url": "https://inference.generativeai.us-ashburn-1.oci.oraclecloud.com/20231130/actions/embedText",
    "model": "cohere.embed-v4.0"
  }';
  l_count NUMBER := 0;
BEGIN
  FOR r IN (
    SELECT doc_id, title, tags, doc_text
    FROM   support_policy_vectors
    WHERE  doc_vector IS NULL
    ORDER  BY doc_id
  ) LOOP
    UPDATE support_policy_vectors
    SET    doc_vector = DBMS_VECTOR.UTL_TO_EMBEDDING(
                            r.title || CHR(10) || r.tags || CHR(10) || r.doc_text,
                            JSON(c_embedding_params)
                         )
    WHERE  doc_id = r.doc_id;

    l_count := l_count + 1;
  END LOOP;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Embedded policy documents: ' || l_count);
END;
/

CREATE VECTOR INDEX idx_support_policy_vec
ON support_policy_vectors (doc_vector)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
DISTANCE COSINE;

CREATE OR REPLACE FUNCTION support_policy_query_vector (
  p_question IN VARCHAR2
) RETURN VECTOR
IS
  c_embedding_params CONSTANT CLOB := '{
    "provider": "ocigenai",
    "credential_name": "GENAI_VECTOR_CRED",
    "url": "https://inference.generativeai.us-ashburn-1.oci.oraclecloud.com/20231130/actions/embedText",
    "model": "cohere.embed-v4.0"
  }';
BEGIN
  RETURN DBMS_VECTOR.UTL_TO_EMBEDDING(p_question, JSON(c_embedding_params));
END;
/

CREATE OR REPLACE FUNCTION search_support_policy (
  p_question IN VARCHAR2,
  p_top_k    IN NUMBER DEFAULT 3
) RETURN CLOB
IS
  l_query_vec VECTOR(1536, FLOAT32);
  l_result    CLOB := EMPTY_CLOB();
BEGIN
  l_query_vec := support_policy_query_vector(p_question);

  FOR r IN (
    SELECT doc_id,
           policy_area,
           title,
           tags,
           doc_text,
           VECTOR_DISTANCE(doc_vector, l_query_vec, COSINE) AS distance
    FROM   support_policy_vectors
    ORDER  BY VECTOR_DISTANCE(doc_vector, l_query_vec, COSINE)
    FETCH  FIRST LEAST(GREATEST(NVL(p_top_k, 3), 1), 5) ROWS ONLY
  ) LOOP
    l_result := l_result
      || '[' || r.doc_id || '] ' || r.title
      || ' / area=' || r.policy_area
      || ' / distance=' || TO_CHAR(ROUND(r.distance, 4))
      || CHR(10)
      || DBMS_LOB.SUBSTR(r.doc_text, 700, 1)
      || CHR(10) || CHR(10);
  END LOOP;

  RETURN l_result;
END;
/

SELECT COUNT(*) AS embedded_docs
FROM   support_policy_vectors
WHERE  doc_vector IS NOT NULL;

SELECT doc_id,
       policy_area,
       title,
       ROUND(VECTOR_DISTANCE(
         doc_vector,
         support_policy_query_vector('주문번호 10248 상품이 파손되었습니다. 반품 승인번호가 필요합니다.'),
         COSINE
       ), 4) AS distance
FROM   support_policy_vectors
ORDER  BY VECTOR_DISTANCE(
          doc_vector,
          support_policy_query_vector('주문번호 10248 상품이 파손되었습니다. 반품 승인번호가 필요합니다.'),
          COSINE
        )
FETCH FIRST 3 ROWS ONLY;

SELECT DBMS_LOB.SUBSTR(
         search_support_policy('재고가 없고 입고 예정인 상품은 고객에게 어떻게 안내해야 하나요?', 3),
         4000,
         1
       ) AS search_result
FROM dual;
